[versions]
agp = "8.8.1"
kotlin = "1.9.24"
googleGmsGoogleServices = "4.4.4"

coreKtx = "1.15.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
navigationFragmentKtx = "2.9.6"
navigationUiKtx = "2.9.6"
legacy = "1.0.0"

playServicesMaps = "18.0.0"
playServicesLocation = "21.3.0"
playServicesAuth = "19.2.0"

runtimePermission = "1.1.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
activity = "1.8.1"

credentials = "1.5.0"
credentialsPlayServicesAuth = "1.5.0"
googleid = "1.1.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-legacy = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacy" }

play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }